% Adds logs for Step 5 transfer completion and server utilization.
addpath(genpath(fullfile(fileparts(mfilename('fullpath')), '..', ...
    'simulink-agentic-toolkit')));
modelName = 'DR_Screening_Capacity_Model';
open_system(modelName);
ops = ['[', ...
    '{"op":"add_block","type":"To Workspace","name":"Sync_Completed","ref":"done","params":{"VariableName":"syncCompleted","SaveFormat":"Timeseries","MaxDataPoints":"inf","SampleTime":"-1"}},', ...
    '{"op":"add_block","type":"To Workspace","name":"Sync_Utilization","ref":"util","params":{"VariableName":"syncUtilization","SaveFormat":"Timeseries","MaxDataPoints":"inf","SampleTime":"-1"}},', ...
    '{"op":"add_block","type":"To Workspace","name":"Sync_Transferred","ref":"sent","params":{"VariableName":"syncTransferred","SaveFormat":"Timeseries","MaxDataPoints":"inf","SampleTime":"-1"}},', ...
    '{"op":"connect","target":"blk_63.y1 -> #done.u1"},', ...
    '{"op":"connect","target":"blk_62.y2 -> #util.u1"},', ...
    '{"op":"connect","target":"blk_62.y1 -> #sent.u1"}', ...
    ']'];
result = model_edit(modelName, 'root', ops, 'incremental');
disp(result);
save_system(modelName);
