function apply_data_driven_telemetry
%APPLY_DATA_DRIVEN_TELEMETRY Configure the model to bootstrap measured arrays.
% Run once in MATLAB after pulling these files. It saves the updated .slx.
model = 'DR_Screening_Capacity_Model';
modelFolder = fileparts(mfilename('fullpath'));
addpath(modelFolder);
open_system(model);
set_param(model, 'InitFcn', "run(fullfile(fileparts(get_param(bdroot,'FileName')),'config.m'));");
set_param([model '/AI_Light_Processing'], ...
    'ServiceTimeSource', 'MATLAB action', ...
    'ServiceTimeAction', 'dt = draw_telemetry_sample(cfg.lightPathLatencies,cfg.lightPathLatency);', ...
    'ServiceCompleteAction', ['coder.extrinsic(''draw_telemetry_sample''); ' ...
    'entity.AIPath = 1; entity.ReviewRoute = 2; ' ...
    'if draw_telemetry_sample(cfg.fullPathRequired,cfg.fullPathProbability), entity.AIPath = 2; end; ' ...
    'if draw_telemetry_sample(cfg.autoClearOutcomes,0), entity.ReviewRoute = 1; end;']);
set_param([model '/AI_Full_Processing'], ...
    'ServiceTimeSource', 'MATLAB action', ...
    'ServiceTimeAction', 'dt = draw_telemetry_sample(cfg.fullPathLatencies,cfg.fullPathLatency);');
set_param([model '/Image_Acquisition'], 'ServiceCompleteAction', [ ...
    'coder.extrinsic(''draw_telemetry_sample''); ' ...
    'if draw_telemetry_sample(cfg.qualityRejected,cfg.qualityRejectRate), ' ...
    'entity.RecaptureAttempts = entity.RecaptureAttempts + 1; ' ...
    'if entity.RecaptureAttempts > cfg.maxRecaptureAttempts, entity.QualityRoute = 3; ' ...
    'else, entity.QualityRoute = 2; end; else, entity.QualityRoute = 1; end;']);
save_system(model);
close_system(model, 0);
fprintf('Updated %s to sample measured telemetry arrays.\n', model);
end
