% Step 5: non-blocking deferred-sync branch.  The Entity Replicator leaves
% the clinical entity on its original route and sends a copy to local sync.
addpath(genpath(fullfile(fileparts(mfilename('fullpath')), '..', ...
    'simulink-agentic-toolkit')));
modelName = 'DR_Screening_Capacity_Model';
config;
open_system(modelName);

ops = ['[', ...
    '{"op":"add_block","type":"Entity Replicator","name":"Processed_Image_Copy","ref":"copy"},', ...
    '{"op":"add_block","type":"Queue","name":"Sync_Queue","ref":"syncQueue","params":{"Capacity":"inf","QueueType":"FIFO","NumberEntitiesDeparted":"on","NumberEntitiesInBlock":"on","AverageWait":"on","AverageQueueLength":"on"}},', ...
    '{"op":"add_block","type":"Entity Gate","name":"Connectivity_Gate","ref":"gate","params":{"OperatingMode":"Toggle gate","OpenGateAtSimulationStart":"off"}},', ...
    '{"op":"add_block","type":"Entity Generator","name":"Connectivity_Controller","ref":"controller","params":{"GenerationMethod":"Time-based","TimeSource":"MATLAB action","GenerateEntityAtSimulationStart":"off","IntergenerationTimeAction":"persistent eventIndex; if isempty(eventIndex), eventIndex = 1; end; dt = cfg.syncEventIntervals(eventIndex); eventIndex = mod(eventIndex,numel(cfg.syncEventIntervals)) + 1;"}},', ...
    '{"op":"add_block","type":"Entity Server","name":"Bandwidth_Transmission","ref":"transmit","params":{"Capacity":"1","ServiceTimeSource":"Dialog","ServiceTimeValue":"cfg.imageSizeMB*8/cfg.bandwidthMbps","NumberEntitiesDeparted":"on","Utilization":"on"}},', ...
    '{"op":"add_block","type":"Entity Terminator","name":"District_Server","ref":"district","params":{"NumberEntitiesArrived":"on"}},', ...
    '{"op":"disconnect","target":"blk_3.y4 -> blk_21.u1"},', ...
    '{"op":"connect","target":"blk_3.y4 -> #copy.u1"},', ...
    '{"op":"connect","target":"#copy.y1 -> blk_21.u1"},', ...
    '{"op":"connect","target":"#copy.y2 -> #syncQueue.u1"},', ...
    '{"op":"connect","target":"#syncQueue.y1 -> #gate.u2"},', ...
    '{"op":"connect","target":"#controller.y2 -> #gate.u1"},', ...
    '{"op":"connect","target":"#gate.y1 -> #transmit.u1"},', ...
    '{"op":"connect","target":"#transmit.y3 -> #district.u1"}', ...
    ']'];
result = model_edit(modelName, 'root', ops, 'incremental');
disp(result);
save_system(modelName);
