% Wires the Step 5 connectivity controller into the existing sync branch.
addpath(genpath(fullfile(fileparts(mfilename('fullpath')), '..', ...
    'simulink-agentic-toolkit')));
modelName = 'DR_Screening_Capacity_Model';
config;
open_system(modelName);
ops = ['[', ...
    '{"op":"configure","target":"blk_61","params":{"OperatingMode":"Enable gate","OpenGateAtSimulationStart":"off"}},', ...
    '{"op":"configure","target":"blk_64","params":{"EntityType":"Anonymous","DataInitialValue":"0","GenerateAction":"persistent isOnline; if isempty(isOnline), isOnline = 1; else, isOnline = 1 - isOnline; end; entity = isOnline;"}},', ...
    '{"op":"disconnect","target":"blk_60.y1 -> blk_61.u1"},', ...
    '{"op":"connect","target":"blk_60.y1 -> blk_61.u2"},', ...
    '{"op":"connect","target":"blk_64.y1 -> blk_61.u1"}', ...
    ']'];
result = model_edit(modelName, 'root', ops, 'incremental');
disp(result);
save_system(modelName);
