function summary = validate_telemetry(telemetryFile)
%VALIDATE_TELEMETRY Print and plot the exact data that the model will sample.
if nargin < 1
    telemetryFile = fullfile(fileparts(mfilename('fullpath')), 'telemetry_measured.mat');
end
loaded = load(telemetryFile, 'telemetry');
if ~isfield(loaded, 'telemetry')
    error('DRCapacity:InvalidTelemetry', '%s does not contain telemetry.', telemetryFile);
end
telemetry = loaded.telemetry;
summary = struct( ...
    'numImages', telemetry.numImages, ...
    'qualityRejectRate', mean(logical(telemetry.qualityRejected)), ...
    'autoClearRate', mean(logical(telemetry.autoClearOutcomes)), ...
    'lightPathLatencyMedianSeconds', median(telemetry.lightPathLatencies), ...
    'lightPathLatencyP95Seconds', prctile(telemetry.lightPathLatencies, 95));
fprintf(['Telemetry source: %s\nImages: %d\nReject rate: %.2f%%\n' ...
    'Auto-clear rate: %.2f%%\nLight latency median/p95: %.3f / %.3f s\n'], ...
    string(telemetry.source), summary.numImages, 100*summary.qualityRejectRate, ...
    100*summary.autoClearRate, summary.lightPathLatencyMedianSeconds, ...
    summary.lightPathLatencyP95Seconds);
figure('Name', 'DR capacity telemetry validation');
histogram(telemetry.lightPathLatencies);
xlabel('Light-path latency (seconds)'); ylabel('Images');
title(sprintf('Measured light-path latency (%d images)', summary.numImages)); grid on;
end
